name: workflow_christian.yml
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # opciones: temurin, zulu, corretto, etc.
          java-version: '17'      # cambia a 11, 21 u otra versión si lo necesitas
          cache: 'maven'

      - name: Compilar con Maven
        run: mvn clean install -B
          
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # para checks y PR decoration
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: |
          mvn -B sonar:sonar \
            -Dsonar.organization=${SONAR_ORGANIZATION} \
            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
            -Dsonar.token="${SONAR_TOKEN}" \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.coverage.jacoco.xmlReportPaths="target/site/jacoco/jacoco.xml"